### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by stocks29** [indiejames/atom-iex#22]
steps to reproduce below:
1. Try to "run all tests in pane"

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: [iex](https://github.com/indiejames/atom-iex) package, v0.9.6
### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At /Users/myusername/.atom/packages/iex/lib/iex.coffee:149

TypeError: Cannot read property 'path' of null
  at Object.module.exports.Iex.runTests (/Users/myusername/.atom/packages/iex/lib/iex.coffee:149:35)
  at atom-workspace.subscriptions.add.atom.commands.add.iex:run-tests (/Users/myusername/.atom/packages/iex/lib/iex.coffee:87:81)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:71:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```
### Commands

```
     -0:45.2.0 iex:run-all-tests (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:38.2.0 iex:open (atom-text-editor.editor.is-focused)
     -0:20.8.0 iex:open-split-down (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:05.7.0 elixir-cmd:build (atom-text-editor.editor.is-focused)
     -0:00.6.0 iex:run-tests (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "projectHome": "/Users/myusername/projects"
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-elixir, v1.2.6
elixir-cmd, v0.2.6
ide-haskell, v0.4.2
iex, v0.9.6
language-elixir, v0.4.0
language-haskell, v1.0.0
linter, v0.12.6
linter-elixirc, v0.2.1
vim-mode, vundefined

# Dev
No dev packages
```

**Comment by indiejames** [comment]
@stocks29 thanks for the detailed bug report. This makes it much easier to reproduce and fix problems. This one was caused by me not checking to see if the active editor was null when attempting to run the tests. I have added the check so now 'run all tests in pane' does nothing if the active pane is not an file editor.
