### ISSUE TITLE
Problem installing on Mac

### ISSUE THREAD

**Issue by lynnwebber** [indiejames/atom-iex#33]
Atom 1.0.19, 
OS X 10.10.5 - XCode installed, command line tools installed
hopefully something easy for you to identify.  Thanks in advance.

```
nstalling “iex@0.9.18” failed.Hide output…

> child_pty@1.1.1 install /private/var/folders/ty/_876170j77s6vnym2hndcyc40000gn/T/apm-install-dir-11595-5134-1t1uu77/node_modules/iex/node_modules/child_pty
> node-gyp rebuild

  CXX(target) Release/obj.target/exechelper/src/exechelper.o
  LINK(target) Release/exechelper

> pty.js@0.2.13 install /private/var/folders/ty/_876170j77s6vnym2hndcyc40000gn/T/apm-install-dir-11595-5134-1t1uu77/node_modules/iex/node_modules/pty.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/pty.node

ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/exechelper] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/ty/_876170j77s6vnym2hndcyc40000gn/T/apm-install-dir-11595-5134-1t1uu77/node_modules/iex/node_modules/child_pty
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/pty.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/ty/_876170j77s6vnym2hndcyc40000gn/T/apm-install-dir-11595-5134-1t1uu77/node_modules/iex/node_modules/pty.js
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/lynn/.atom/.apm/.apmrc" "--userconfig" "/Users/lynn/.atom/.apmrc" "install" "/private/var/folders/ty/_876170j77s6vnym2hndcyc40000gn/T/d-11595-5134-1u98n7z/package.tgz" "--target=0.30.7" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! child_pty@1.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the child_pty@1.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the child_pty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls child_pty
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/ty/_876170j77s6vnym2hndcyc40000gn/T/apm-install-dir-11595-5134-1t1uu77/npm-debug.log
```

**Comment by dmoulton** [comment]
Having the same issue. Is there a resolution for this?

**Comment by indiejames** [comment]
Sorry, just saw this. child_pty causing problems again. I will take a look.

**Comment by bigardone** [comment]
Hi!
I have this problem too, any posible solution?
Thanks!
